<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="19" failures="12" name="io.cloudboost.CloudObjectTest" time="0.201" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.60-b23"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/media/ranjeet/CED23D64D23D52476/cloudboost/JavaSDK/JavaSDK"/>
    <property name="java.runtime.version" value="1.8.0_60-b27"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="3.13.0-53-generic"/>
    <property name="user.home" value="/root"/>
    <property name="user.timezone" value="Asia/Kolkata"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="root"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher package"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_60"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveRelation" time="0.011">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$11.done(CloudObjectTest.java:242)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.saveRelation(CloudObjectTest.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;Sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;sameRelation&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;samplet&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;,&quot;sameRelation&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="SaveData" time="0.013">
    <failure message="Failed to save data" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Failed to save data
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$1.done(CloudObjectTest.java:32)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.SaveData(CloudObjectTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;samplexyz&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="ShouldNotSaveStringIntoDate" time="0.008"/>
  <testcase classname="io.cloudboost.CloudObjectTest" name="ShouldNotSaveWithoutRequiredColumn" time="0.011"/>
  <testcase classname="io.cloudboost.CloudObjectTest" name="ShouldNotSaveWithWrongDataType" time="0.01"/>
  <testcase classname="io.cloudboost.CloudObjectTest" name="ShouldNotSaveDuplicateValue" time="0.009">
    <failure message="Should save the data" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Should save the data
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$5.done(CloudObjectTest.java:122)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.ShouldNotSaveDuplicateValue(CloudObjectTest.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;unique&quot;:&quot;jhrwobru&quot;,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;,&quot;unique&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="updateAfterSave" time="0.019">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$6.done(CloudObjectTest.java:137)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.updateAfterSave(CloudObjectTest.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="deleteAfterSave" time="0.009">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$7.done(CloudObjectTest.java:161)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.deleteAfterSave(CloudObjectTest.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveArray" time="0.01">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$8.done(CloudObjectTest.java:187)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.saveArray(CloudObjectTest.java:183)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;stringArray&quot;:[&quot;osnkiubi&quot;,&quot;osnkiubi&quot;],&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;,&quot;stringArray&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveArrayWithWrongDataType" time="0.012"/>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveArrayWithJSONObject" time="0.01">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$10.done(CloudObjectTest.java:224)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.saveArrayWithJSONObject(CloudObjectTest.java:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;objectArray&quot;:[{&quot;sample&quot;:&quot;sample&quot;},{&quot;sample&quot;:&quot;sample&quot;}],&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;,&quot;objectArray&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveRelationWithRelate" time="0.01">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$12.done(CloudObjectTest.java:259)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.saveRelationWithRelate(CloudObjectTest.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="keepRelationIntact" time="0.012">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$13.done(CloudObjectTest.java:286)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.keepRelationIntact(CloudObjectTest.java:282)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;newColumn2&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Custom3&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;]},&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Custom2&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;newColumn2&quot;,&quot;newColumn7&quot;],&quot;newColumn7&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;student1&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;]}},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveWrongRelation" time="0.011"/>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveEmptyArrayOfCloudObject" time="0.015">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$15.done(CloudObjectTest.java:332)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.saveEmptyArrayOfCloudObject(CloudObjectTest.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveArrayOfCloudObject" time="0.014">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$16.done(CloudObjectTest.java:361)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.saveArrayOfCloudObject(CloudObjectTest.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="updateListAfterSave" time="0.01">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudObjectTest$17.done(CloudObjectTest.java:391)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudObjectTest.updateListAfterSave(CloudObjectTest.java:387)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;sample&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_tableName&quot;:&quot;Sample&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;name&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveJSON" time="0.001"/>
  <testcase classname="io.cloudboost.CloudObjectTest" name="saveArrayOfGeoPoint" time="0.001"/>
</testsuite>