<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="11" failures="2" name="io.cloudboost.CloudSearchTest" time="0.171" errors="9" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/amd64"/>
    <property name="java.vm.version" value="25.60-b23"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=":"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="/media/ranjeet/CED23D64D23D52476/cloudboost/JavaSDK/JavaSDK"/>
    <property name="java.runtime.version" value="1.8.0_60-b27"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="line.separator" value="
"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="os.name" value="Linux"/>
    <property name="classworlds.conf" value="/usr/share/maven/bin/m2.conf"/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="3.13.0-53-generic"/>
    <property name="user.home" value="/root"/>
    <property name="user.timezone" value="Asia/Kolkata"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="user.name" value="root"/>
    <property name="java.class.path" value="/usr/share/maven/boot/plexus-classworlds-2.x.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-oracle/jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher package"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_60"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-oracle/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="securerandom.source" value="file:/dev/./urandom"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="/usr/share/maven"/>
    <property name="file.separator" value="/"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchindexedObject" time="0.022">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;query&quot;:{&quot;should&quot;:[{&quot;match&quot;:{&quot;description&quot;:{&quot;fuzziness&quot;:null,&quot;minimum_shoul_match&quot;:null,&quot;query&quot;:&quot;wi-fi&quot;,&quot;boost&quot;:null,&quot;operator&quot;:null}}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}
http://localhost:4730/data/sample123/Custom1/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;query&quot;:{&quot;should&quot;:[{&quot;match&quot;:{&quot;description&quot;:{&quot;fuzziness&quot;:null,&quot;minimum_shoul_match&quot;:null,&quot;query&quot;:&quot;wi-fi&quot;,&quot;boost&quot;:null,&quot;operator&quot;:null}}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Custom1&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="indexData" time="0.013">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudSearchTest$3.done(CloudSearchTest.java:70)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudSearchTest.indexData(CloudSearchTest.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;name&quot;:&quot;Ranjeet Kumar&quot;,&quot;description&quot;:&quot;Ranjeet&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_isSearchable&quot;:true,&quot;_tableName&quot;:&quot;Student&quot;,&quot;class&quot;:&quot;Java&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;description&quot;,&quot;age&quot;,&quot;name&quot;,&quot;class&quot;],&quot;age&quot;:19},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchObjectForValue" time="0.016">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;filter&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[],&quot;must&quot;:[{&quot;term&quot;:{&quot;age&quot;:19}}]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;filter&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[],&quot;must&quot;:[{&quot;term&quot;:{&quot;age&quot;:19}}]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchObjectWithPhrase" time="0.023">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;query&quot;:{&quot;should&quot;:[{&quot;match&quot;:{&quot;name&quot;:{&quot;type&quot;:&quot;pharse&quot;,&quot;slop&quot;:null}}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;query&quot;:{&quot;should&quot;:[{&quot;match&quot;:{&quot;name&quot;:{&quot;type&quot;:&quot;pharse&quot;,&quot;slop&quot;:null}}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchObjectWithWildCard" time="0.012">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>bool :: {&quot;query&quot;:{&quot;should&quot;:[{&quot;wildcard&quot;:{&quot;name&quot;:{&quot;value&quot;:&quot;R*&quot;}}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;query&quot;:{&quot;should&quot;:[{&quot;wildcard&quot;:{&quot;name&quot;:{&quot;value&quot;:&quot;R*&quot;}}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchObjectWithStartsWith" time="0.016">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;query&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[],&quot;must&quot;:[{&quot;prefix&quot;:{&quot;name&quot;:{&quot;value&quot;:&quot;R&quot;}}}]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;query&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[],&quot;must&quot;:[{&quot;prefix&quot;:{&quot;name&quot;:{&quot;value&quot;:&quot;R&quot;}}}]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchObjectWithMostColumn" time="0.013">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;query&quot;:{&quot;should&quot;:[{&quot;multi_match&quot;:{&quot;type&quot;:&quot;most_fields&quot;}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;query&quot;:{&quot;should&quot;:[{&quot;multi_match&quot;:{&quot;type&quot;:&quot;most_fields&quot;}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchObjectWithBestColumn" time="0.011">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;query&quot;:{&quot;should&quot;:[{&quot;multi_match&quot;:{&quot;type&quot;:&quot;best_fields&quot;}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;query&quot;:{&quot;should&quot;:[{&quot;multi_match&quot;:{&quot;type&quot;:&quot;best_fields&quot;}}],&quot;must_not&quot;:[],&quot;must&quot;:[]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="searchObjectWithNotEqualTo" time="0.01">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;filter&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[],&quot;must&quot;:[{&quot;term&quot;:{&quot;age&quot;:19}}]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;filter&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[],&quot;must&quot;:[{&quot;term&quot;:{&quot;age&quot;:19}}]}}},&quot;limit&quot;:10,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="limitNumberOfSearch" time="0.018">
    <error message="java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="java.util.concurrent.ExecutionException">java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.future.NettyResponseFuture.abort(NettyResponseFuture.java:231)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:137)
	at com.ning.http.client.providers.netty.request.NettyConnectListener.operationComplete(NettyConnectListener.java:145)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:409)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:400)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:362)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at com.ning.http.client.providers.netty.request.NettyConnectListener.onFutureFailure(NettyConnectListener.java:133)
	... 13 more
Caused by: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:152)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 more
</error>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
bool :: {&quot;filter&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[{&quot;term&quot;:{&quot;age&quot;:19}}],&quot;must&quot;:[]}}
http://localhost:4730/data/sample123/Student/search
{&quot;query&quot;:{&quot;filtered&quot;:{&quot;filter&quot;:{&quot;should&quot;:[],&quot;must_not&quot;:[{&quot;term&quot;:{&quot;age&quot;:19}}],&quot;must&quot;:[]}}},&quot;limit&quot;:0,&quot;skip&quot;:0,&quot;sort&quot;:[],&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;,&quot;collectionName&quot;:&quot;Student&quot;}
</system-out>
  </testcase>
  <testcase classname="io.cloudboost.CloudSearchTest" name="indexObject" time="0.013">
    <failure message="java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: java.util.concurrent.ExecutionException: java.net.ConnectException: Connection refused: localhost/127.0.0.1:4730
	at junit.framework.Assert.fail(Assert.java:47)
	at io.cloudboost.CloudSearchTest$1.done(CloudSearchTest.java:29)
	at io.cloudboost.CloudObject.save(CloudObject.java:530)
	at io.cloudboost.CloudSearchTest.indexObject(CloudSearchTest.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
	at org.junit.internal.runners.statements.FailOnTimeout$1.run(FailOnTimeout.java:28)
</failure>
    <system-out>SQL Lite is Up
Driver name: SQLiteJDBC
Driver version: native
Product name: SQLite
Product version: 3.8.11
Table Created
Socket Initializaed
{&quot;document&quot;:{&quot;expires&quot;:null,&quot;_isModified&quot;:true,&quot;_type&quot;:&quot;custom&quot;,&quot;description&quot;:&quot;wi-fi&quot;,&quot;ACL&quot;:{&quot;read&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}},&quot;write&quot;:{&quot;allow&quot;:{&quot;role&quot;:[],&quot;user&quot;:[&quot;all&quot;]},&quot;deny&quot;:{&quot;role&quot;:[],&quot;user&quot;:[]}}},&quot;_isSearchable&quot;:true,&quot;_tableName&quot;:&quot;Custom1&quot;,&quot;_modifiedColumns&quot;:[&quot;createdAt&quot;,&quot;updatedAt&quot;,&quot;ACL&quot;,&quot;expires&quot;,&quot;description&quot;]},&quot;key&quot;:&quot;9SPxp6D3OPWvxj0asw5ryA==&quot;}
</system-out>
  </testcase>
</testsuite>